import medicine_infectious_disease_epidemiology_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace medicine_infectious_disease_epidemiology_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end medicine_infectious_disease_epidemiology_theorem_canonical_lane_mathlib
end HautevilleHouse
